# Generated by Django 4.0.4 on 2022-07-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Foodlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200)),
                ('nation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.nation')),
            ],
        ),
    ]
